---
- name: Установка Zabbix на Ubuntu
  hosts: zabbix
  become: true
  vars:
    zabbix_db_password: "Password@2026"

  tasks:

    - name: Обновление списка пакетов
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Установка необходимых пакетов
      apt:
        name:
          - wget
          - apache2
          - postgresql
          - postgresql-contrib
          - php
          - libapache2-mod-php
          - php-pgsql
          - php-mbstring
          - php-gd
          - php-xml
          - php-bcmath
          - python3-psycopg2
        state: present

  
    - name: Скачивание репозитория Zabbix
      get_url:
        url: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb"
        dest: /tmp/zabbix-release.deb

    - name: Установка репозитория Zabbix
      apt:
        deb: /tmp/zabbix-release.deb

    - name: Обновление списка пакетов
      apt:
        update_cache: yes


    - name: Установка Zabbix Server, Frontend, Agent и SQL-скриптов
      apt:
        name:
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - zabbix-sql-scripts
          - zabbix-agent
          - zabbix-apache-conf
        state: present

    - name: Запуск PostgreSQL
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Создание пользователя БД
      shell: |
        sudo -u postgres psql -c "CREATE USER zabbix WITH PASSWORD '{{ zabbix_db_password }}';"
      register: create_user
      failed_when: create_user.rc != 0 and "already exists" not in create_user.stderr
      changed_when: "create_user.rc == 0"

    - name: Создание базы данных
      shell: |
        sudo -u postgres psql -c "CREATE DATABASE zabbix OWNER zabbix;"
      register: create_db
      failed_when: create_db.rc != 0 and "already exists" not in create_db.stderr
      changed_when: "create_db.rc == 0"

    - name: Импорт схемы базы данных
      shell: |
        gunzip -c /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | PGPASSWORD={{ zabbix_db_password }} psql -U zabbix -h localhost -d zabbix
      register: import_schema
      failed_when: import_schema.rc != 0
      changed_when: import_schema.rc == 0
      timeout: 300

    - name: Настройка подключения к БД
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: "^{{ item.option }}="
        line: "{{ item.option }}={{ item.value }}"
      loop:
        - { option: 'DBHost', value: 'localhost' }
        - { option: 'DBName', value: 'zabbix' }
        - { option: 'DBUser', value: 'zabbix' }
        - { option: 'DBPassword', value: "{{ zabbix_db_password }}" }
      notify: restart zabbix-server

    - name: Настройка часового пояса PHP
      lineinfile:
        path: /etc/php/8.1/apache2/php.ini
        regexp: '^;?date.timezone ='
        line: 'date.timezone = Europe/Moscow'

    - name: Включение конфигурации Zabbix в Apache
      command: a2enconf zabbix
      notify: restart apache2

    - name: Запуск Apache
      service:
        name: apache2
        state: restarted
        enabled: yes

    - name: Запуск Zabbix Server
      service:
        name: zabbix-server
        state: started
        enabled: yes

    - name: Запуск Zabbix Agent
      service:
        name: zabbix-agent
        state: started
        enabled: yes

  handlers:
    - name: restart zabbix-server
      service:
        name: zabbix-server
        state: restarted

    - name: restart apache2
      service:
        name: apache2
        state: restarted