[all:vars]
ansible_user = zolotorev
ansible_ssh_private_key_file = ~/.ssh/id_ed25519
ansible_ssh_extra_args = -o StrictHostKeyChecking=no

[bastion]
bastion ansible_host=1111.88.245.175

[webservers]
web-1 ansible_host=web-1.ru-central1.internal ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -p 22 zolotorev@111.88.245.175"'
web-2 ansible_host=web-2.ru-central1.internal ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -p 22 zolotorev@111.88.245.175"'

[zabbix]
zabbix ansible_host=zabbix.ru-central1.internal ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -p 22 zolotorev@111.88.245.175"'